// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1nTkkW146Dx9k3GaTH2YfoixNGC2eMwE',
    appId: '1:72433468106:web:af40868f8eadaa56126a33',
    messagingSenderId: '72433468106',
    projectId: 'mobai-wms',
    authDomain: 'mobai-wms.firebaseapp.com',
    storageBucket: 'mobai-wms.firebasestorage.app',
    measurementId: 'G-ZN8XHL6W9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0MKZXNrY2OF_Az9H2b2RqVzNiUk_KhI8',
    appId: '1:72433468106:android:802c7d4f2293f634126a33',
    messagingSenderId: '72433468106',
    projectId: 'mobai-wms',
    storageBucket: 'mobai-wms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFLO2w_F_ZQyiT83-wYEwKgAq3PctnM48',
    appId: '1:72433468106:ios:11831d43f89eb52a126a33',
    messagingSenderId: '72433468106',
    projectId: 'mobai-wms',
    storageBucket: 'mobai-wms.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFLO2w_F_ZQyiT83-wYEwKgAq3PctnM48',
    appId: '1:72433468106:ios:11831d43f89eb52a126a33',
    messagingSenderId: '72433468106',
    projectId: 'mobai-wms',
    storageBucket: 'mobai-wms.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1nTkkW146Dx9k3GaTH2YfoixNGC2eMwE',
    appId: '1:72433468106:web:608bed5d4c4702c6126a33',
    messagingSenderId: '72433468106',
    projectId: 'mobai-wms',
    authDomain: 'mobai-wms.firebaseapp.com',
    storageBucket: 'mobai-wms.firebasestorage.app',
    measurementId: 'G-DGX9PG6REL',
  );
}
