"""
Order repository for Firestore operations.
"""

from typing import List, Optional, Dict, Any

from app.repositories.base_repository import BaseRepository
from app.core.enums import OrderType, OrderStatus


class OrderRepository(BaseRepository):
    """Repository for Order documents."""

    def __init__(self):
        super().__init__("orders")

    async def get_by_type(self, order_type: OrderType) -> List[Dict[str, Any]]:
        """Get orders by type."""
        return await self.query(filters=[("type", "==", order_type.value)])

    async def get_by_status(self, status: OrderStatus) -> List[Dict[str, Any]]:
        """Get orders by status."""
        return await self.query(filters=[("status", "==", status.value)])

    async def get_pending_orders(self) -> List[Dict[str, Any]]:
        """Get all pending orders."""
        return await self.query(filters=[("status", "==", OrderStatus.PENDING.value)])

    async def get_ai_generated_orders(self) -> List[Dict[str, Any]]:
        """Get orders generated by AI."""
        return await self.query(filters=[("generated_by_ai", "==", True)])

    async def get_overridden_orders(self) -> List[Dict[str, Any]]:
        """Get overridden orders."""
        return await self.query(filters=[("status", "==", OrderStatus.OVERRIDDEN.value)])

    async def get_filtered(
        self,
        order_type: Optional[OrderType] = None,
        status_filter: Optional[OrderStatus] = None,
        ai_generated_only: bool = False,
    ) -> List[Dict[str, Any]]:
        """Get orders with optional filters."""
        filters = []
        if order_type:
            filters.append(("type", "==", order_type.value))
        if status_filter:
            filters.append(("status", "==", status_filter.value))
        if ai_generated_only:
            filters.append(("generated_by_ai", "==", True))
        return await self.query(filters=filters if filters else None)
