"""
Order model with order lines for warehouse commands.
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel as PydanticBaseModel, Field

from app.models.base import BaseModel
from app.core.enums import OrderType, OrderStatus


class OrderLine(PydanticBaseModel):
    """A single line within an order."""

    product_id: str = Field(..., description="Product ID")
    sku: Optional[str] = Field(default=None, description="Product SKU")
    product_name: Optional[str] = Field(default=None, description="Product name")
    quantity: int = Field(..., gt=0, description="Ordered quantity")
    source_x: Optional[int] = Field(default=None, description="Source X coordinate")
    source_y: Optional[int] = Field(default=None, description="Source Y coordinate")
    source_z: Optional[int] = Field(default=None, description="Source Z coordinate")
    source_floor: Optional[int] = Field(default=None, description="Source floor")
    destination_x: Optional[int] = Field(default=None, description="Destination X coordinate")
    destination_y: Optional[int] = Field(default=None, description="Destination Y coordinate")
    destination_z: Optional[int] = Field(default=None, description="Destination Z coordinate")
    destination_floor: Optional[int] = Field(default=None, description="Destination floor")

    class Config:
        from_attributes = True


class Order(BaseModel):
    """Represents a warehouse order (command, preparation, picking)."""

    type: OrderType = Field(..., description="Order type")
    status: OrderStatus = Field(default=OrderStatus.PENDING, description="Order status")
    lines: List[OrderLine] = Field(default_factory=list, description="Order lines")
    generated_by_ai: bool = Field(default=False, description="Whether generated by AI")
    overridden_by: Optional[str] = Field(default=None, description="User ID who overrode the order")
    override_reason: Optional[str] = Field(default=None, description="Reason for override")
    completed_at: Optional[datetime] = Field(default=None, description="Completion timestamp")
    completed_by: Optional[str] = Field(default=None, description="User ID who completed")

    def to_firestore(self) -> dict:
        """Convert to Firestore-compatible dict."""
        data = super().to_firestore()
        # Serialize order lines
        data["lines"] = [line.model_dump() for line in self.lines]
        if self.completed_at:
            data["completed_at"] = self.completed_at.isoformat()
        return data
